add books-module containing (create, display,update and delete) views
ecitizen-ke/brian-python-training pull request #10
Opened 2024-05-31 06:05 UTC by Brianktoo

add `create, display, update and delete features` to manipulate books dictionary list

2024-05-31 07:00 UTC, codetaskmaster commented on library-management-system/.gitignore
> +.env
Whitespace!

2024-05-31 07:01 UTC, codetaskmaster requested changes

2024-05-31 07:01 UTC, codetaskmaster commented on library-management-system/app/__init__.py
> +    return app
Whitespace!

2024-05-31 07:26 UTC, Brianktoo commented on library-management-system/.gitignore
> +.env
Done

2024-06-01 07:46 UTC, codetaskmaster approved these changes

2024-06-01 07:46 UTC, codetaskmaster commented
LGTM! Proceed

2024-06-02 06:26 UTC, merged

2024-06-02 12:15 UTC, codetaskmaster reviewed
Great job @Brianktoo 

LGTM. Proceed!