added home_page_app
ecitizen-ke/brian-python-training pull request #4
Opened 2024-05-26 10:33 UTC by Brianktoo

add `home_page_app feature` to display our landing page

2024-05-26 11:46 UTC, Brianktoo commented
kindly review this for me

2024-05-27 06:30 UTC, codetaskmaster requested changes

2024-05-27 06:30 UTC, codetaskmaster commented on flask-contact-form-app/.gitignore
> +*/__pycache__/
Add whitespace!

2024-05-27 19:46 UTC, Brianktoo commented on flask-contact-form-app/.gitignore
> +*/__pycache__/
done

2024-05-27 19:52 UTC, Brianktoo commented
add `home_page_app feature`

2024-05-27 19:53 UTC, merged